### ISSUE TITLE
Update job using web editor fails

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-spring-driver#31]
When trying to modify a stored job using the "Edit metadata" button, the server returns error 500.
Modifying the process graph succeeds but the name is being changed.

**Comment by clausmichele** [comment]
This works fine now.

**Comment by pierocampa** [comment]
I believe this should be the fix:
[Batch jobs for ODC back-end. Fixed process.json output and job updating.](../commit/8738636)
