### ISSUE TITLE
Error 400: no jobs are available at the moment

### ISSUE THREAD

**Issue by pierocampa** [Open-EO/openeo-spring-driver#66]
This error keeps popping up (lower-right corner popup) when you enter the editor and have **no** batch jobs saved in your processing library.

"An empty job list should never return a 400 status code. Instead it should return an empty list with a 200 status code."
https://github.com/Open-EO/openeo-web-editor/issues/282

The flowed logic can be found in the [JobsApiController](../blob/1.1-draft/src/main/java/org/openeo/spring/api/JobsApiController.java#L715-L720) class.

**Comment by clausmichele** [comment]
Thanks @pierocampa , I merged your PR!

**Comment by clausmichele** [comment]
Thanks for reporting, I will check!

**Comment by pierocampa** [comment]
@m-mohr : on which branch are you?
No 404 error is possible in the [GET /jobs logic](..//blob/master/src/main/java/org/openeo/spring/api/JobsApiController.java#L692-L720) now (on `master`): on empty list, 200 OK.

**Comment by m-mohr** [comment]
I'm on whatever you've deployed https://openeo.eurac.edu

**Comment by pierocampa** [comment]
Ah ok, I'll let this to you @clausmichele then.
Thanks Matthias for reporting!
