### ISSUE TITLE
Stop a job

### ISSUE THREAD

**Issue by pierocampa** [Open-EO/openeo-spring-driver#68]
The possibility to cancel an ongoing job is currently not implemented. As per [openEO API](https://api.openeo.org/#tag/Data-Processing/operation/stop-job), this means that a client could trigger a: 

    HTTP DELETE /jobs/{job_id}/results

..to cancel the job with the given identifier.

In addition, if the server reaches an inconsistent state on a job (e.g. a missed exception), then the job stays *queued* forever with no option to reset its state.

**Comment by clausmichele** [comment]
The functionality for stopping a job on the ODC back-end has been implemented some time ago, I forgot to close this.
