### ISSUE TITLE
Implement "reduce_spatial" process for the ODC backend

### ISSUE THREAD

**Issue by pierocampa** [Open-EO/openeo-spring-driver#72]
Equivalent of issue #71, for the ODC backend.

**Comment by clausmichele** [comment]
Currently a similar result can be obtained using aggregate_spatial, where multiple polygons can be specified.
This would be an easier case, I will draft an implementation soon.

**Comment by clausmichele** [comment]
Implemented here: https://github.com/Open-EO/openeo-processes-dask/blob/5d0825bd0fe4b7f93cbfcc47392352b927f77f0c/openeo_processes_dask/process_implementations/cubes/reduce.py#L49
