### ISSUE TITLE
Split the log4j logs into separate files

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-spring-driver#75]
Currently log4j dumps everything into a single file. It would be better to make it write on different files depending on the date.

**Comment by pierocampa** [comment]
Here's an example of rolling file appender:
https://github.com/Open-EO/openeo-spring-driver/blob/darestech/src/main/resources/log4j2.xml#L4-L15

Official Log4J docs: https://logging.apache.org/log4j/2.x/manual/appenders.html#RollingFileAppender

**Comment by clausmichele** [comment]
This has been implemented some time ago but was not pushed. I added it with this commit: https://github.com/Open-EO/openeo-spring-driver/commit/2fd2c353afe3d4ee03a2a994ed12d5269f09177e

We need to document the env variable OPENEO_LOGS_DIR which is used in it.

**Comment by pierocampa** [comment]
> This has been implemented some time ago but was not pushed. I added it with this commit: [2fd2c35](https://github.com/Open-EO/openeo-spring-driver/commit/2fd2c353afe3d4ee03a2a994ed12d5269f09177e)
> 
> We need to document the env variable OPENEO_LOGS_DIR which is used in it.

194b83e + ebf44a8
