### ISSUE TITLE
Endpoint GET /jobs does not return JSON

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-spring-driver#82]
When accessing https://openeo.eurac.edu/jobs, one receives an HTML document titled "Whitelabel Error Page" and further stating:

> This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Jun 13 18:19:05 CEST 2023
There was an unexpected error (type=Internal Server Error, status=500).

Possibly related to #66.

**Comment by christophfriedrich** [comment]
For replication purposes maybe I should add that this occurred to me when just accessing the URL in a browser window, i.e. without any login being present -- maybe the behaviour changes if one is logged in. But in any case, the response should have a different format ;)

**Comment by clausmichele** [comment]
Thanks @christophfriedrich. Sorry but I didn't see this issue!

We would need to return a proper message https://api.openeo.org/#tag/Batch-Jobs/operation/list-jobs

@pierocampa I tag you just FYI
