### ISSUE TITLE
Allow processing extension in STAC Collection result

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-spring-driver#98]
Currently, if the returned STAC Collection (generated with raster2stac) returned from the openeo_odc_driver to the openeo-spring-driver include additional fields (like the processing extension: https://github.com/stac-extensions/processing) the spring driver crashes because it doesn't know how to handle those fields.

Sample result STAC from CDSE including processing extension: https://openeo.dataspace.copernicus.eu/openeo/1.2/jobs/j-240806b0429044aa975027bd02e9a226/results/NWFkOThhZjAtZDQ2ZS00MDk0LTg0Y2EtZGJjM2FlMjllNmE5/26aef1829bad9b896380dd73f63bac11?expires=1725009588

**Comment by pierocampa** [comment]
> *The link to the batch job result has expired. Please request the results again.*

@clausmichele, can you refresh the link?

**Comment by pierocampa** [comment]
Anyway, are you adding the process graph's JSON definition as a `processing:expression` element? With which `format`?

Any other [fields](https://github.com/stac-extensions/processing?tab=readme-ov-file#fields) to be expected?

**Comment by clausmichele** [comment]
Here you can find a valid link: https://openeo.dataspace.copernicus.eu/openeo/1.2/jobs/j-240806b0429044aa975027bd02e9a226/results/NWFkOThhZjAtZDQ2ZS00MDk0LTg0Y2EtZGJjM2FlMjllNmE5/d60e33376f8ae035172f7e16c58561e8?expires=1725893530

**Comment by pierocampa** [comment]
PS see 6b99766a

**Comment by clausmichele** [comment]
I confirm that it works using the latest updates.

**Comment by pierocampa** [comment]
Ok, thank you @clausmichele, I will proceed with the merges to master of both [`ogc-testbed-19`](../tree/ogc-testbed-19) and [`feature/stac_results`](../tree/feature/stac_results).

**Comment by pierocampa** [comment]
Closing this issue: the test collection used to mark this as passed can be found here: [`stac_collection_processing.200.json`](../blob/feature/stac_results/src/test/resources/job_results/stac_collection_processing.200.json)
